tutorial 1:explore numpy library to analyze data

1find diff between python list and numpy array
2.why numpy is faster then list
3.where numpy is used

In [324]:
pip install numpy

Requirement already satisfied: numpy in c:\users\tanvir\appdata\local\programs\python\python314\lib\site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: c:\Users\Tanvir\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

In [325]:
import numpy as np

In [326]:
#list
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]

#2. create 1D array with 5 element

In [327]:
#2. create 1D array with 5 element
x = np.array([10,20,30,40,50])
x

array([10, 20, 30, 40, 50])

In [328]:
x=np.random.rand(5)
x

array([0.02206781, 0.14945682, 0.28972837, 0.90833303, 0.60910392])

In [329]:
x=np.random.randint(5,16,10)
x

array([ 8,  8, 10,  9, 15, 11,  8, 14, 10,  7], dtype=int32)

configration

In [330]:
22.#5.create 2D array - 4 by 3
y=np.array([[1,2,3],[4,5,6],[4,3,2],[7,8,2]])
print(y)

[[1 2 3]
 [4 5 6]
 [4 3 2]
 [7 8 2]]

In [331]:
y[-1-2]

array([4, 5, 6])

In [332]:
y=np.random.randint(1,100,5)

In [333]:
#8. create 3D array
z=np.array([[[1,2,3],[4,5,6]],[[4,3,2,],[7,8,2]]])
print(z)

[[[1 2 3]
  [4 5 6]]

 [[4 3 2]
  [7 8 2]]]

In [334]:
a = np.zeros( (3,4),dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [335]:
a = np.ones( (3,4),dtype=int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [336]:
a=np.full((5,5),4)
a

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [337]:
a= 5 * np.eye(4,5,dtype=int)
print(a)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]]

In [338]:
print("shape of a:" , a.shape)

shape of a: (4, 5)

In [339]:
x.ndim
a.dtype

dtype('int64')

In [340]:
print(x.min())

7

In [341]:
print(x.max())

15

In [342]:
print(x.argmin())

9

In [343]:
print(x.argmax())

4

In [344]:
print(x.mean())

10.0

what is indexing?
---->indexing is used to acecss  element in lists, array,string or other data base ture.
---->0 base indexing in python
--->in 2d aindexing is requried row and column

In [345]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [346]:
a[-2]

np.int64(8)

In [347]:
y

array([51, 39,  2,  1, 65], dtype=int32)

slicing refers to the process of extracting a portion of an array or a subarray.

In [348]:
a[2:6]

array([3, 4, 5, 6])

In [349]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [350]:
a[5:]

array([6, 7, 8, 9])

In [351]:
a[:] = 100

In [352]:
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [353]:
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

In [354]:
a[1:8:2]

array([100, 100, 100, 100])

In [355]:
np.flip(a)

array([100, 100, 100, 100, 100, 100, 100, 100, 100])

Tutorial : 2 - Explore Pandas library to analyze  and manipulate data.

--->panda is an open source library for real world data analysis in python.
---->it is built on top of numpy.

***the basic data stricture of pandas are series and dataframe.
--->1) series: series is a one dimensional labeled array.
--->2) dataframe: a dataframe in pandas is a two- dimentional tabular data structure similar to a spre

In [356]:
pip install pandas

Requirement already satisfied: pandas in c:\users\tanvir\appdata\local\programs\python\python314\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tanvir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tanvir\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\tanvir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tanvir\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\tanvir\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: c:\Users\Tanvir\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

In [357]:
import pandas as pd

In [358]:
# 3.Define series with 3 elements.
s1 = pd.Series([1,2,3,])
print(s1)

0    1
1    2
2    3
dtype: int64

In [359]:
#Define a series with a custom index
s2 = pd.Series([1,2,3],["A","B","C"])
print(s2);

A    1
B    2
C    3
dtype: int64

home question
q1.find a diffrence between list 1d numpy arrray and series

In [360]:
# 4.Fetch Series value and index.
print(s2.values)
print(s2.index)

[1 2 3]
Index(['A', 'B', 'C'], dtype='object')

In [361]:
# 5.Create DataFrame from list of Dict.

data =  [{ 'name': 'subodh', 'mark' :28 },
         { 'name': 'ram' , 'mark': 27},
         { 'name': 'abdul', },
         { 'name': 'john', 'mark' : 28}]
f1 = pd.DataFrame(data)
print(f1)

     name  mark
0  subodh  28.0
1     ram  27.0
2   abdul   NaN
3    john  28.0

In [362]:

f1.isna().sum()

name    0
mark    1
dtype: int64

In [363]:
iris = pd.read_csv("iris.csv")

In [364]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal.Length  150 non-null    float64
 1   Sepal.Width   150 non-null    float64
 2   Petal.Length  150 non-null    float64
 3   Petal.Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [365]:
iris.head(10)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [366]:
iris.tail()

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [367]:
iris.isna().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [368]:
iris.index

RangeIndex(start=0, stop=150, step=1)

In [369]:
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [370]:
iris =iris.rename(columns=
                  {'Sepal.Length' : 'Sepal_Length','Sepal.Width' : 'Sepal_Width','Petal.Length': 'Petal_Length','Petal.Width':'Petal_Width'})

In [371]:
iris.columns

Index(['Sepal_Length', 'Sepal_Width', 'Petal_Length', 'Petal_Width',
       'Species'],
      dtype='object')

In [372]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [373]:
iris['Species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [374]:
iris.replace("Iris-Setosa" , "setosa" , inplace=True)
iris.replace("versicolor","versicolor" ,inplace=True)
iris.replace("virginica","virginica" ,inplace=True)

In [375]:
iris[['Petal.Length','Petal.Width']]

KeyError: "None of [Index(['Petal.Length', 'Petal.Width'], dtype='object')] are in the [columns]"

In [ ]:
iris.columns

In [ ]:
def yes_no(Sepal_Length):
    return 'Yes' if Sepal_Length >= 5 else 'No'

# apply function to create a new column
iris['result'] = iris['Sepal_Length'].apply(yes_no)
iris

In [ ]:
iris.info()

In [ ]:
iris.drop('result',axis=1, inplace=True)

In [ ]:
iris[iris['Petal_Length']>5]

In [ ]:
iris(iris['Petal_Length']>6) & (iris['Species'] =='')

In [ ]:
9

1.read dataset student_info.csv

In [ ]:
student = pd.read_csv("student_info.csv")

In [ ]:
student.info()

In [ ]:
student.columns

In [ ]:
student.describe()

In [ ]:
student.isna().sum()

In [ ]:
student['study_hours'] =student['study_hours'].fillna(student['study_hours'].mean())

In [ ]:
student.isna().sum()

In [ ]:
student.mean()

In [ ]:
student.head()

In [ ]:
pip install ucimlrepo

In [ ]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
adult = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets 
  
# metadata 
print(adult.metadata) 
  
# variable information 
print(adult.variables)

In [ ]:
X.info()

In [ ]:
X.isna().sum()

In [ ]:
X.describe()

In [ ]:
X.head()

In [ ]:
X['workclass'].unique()